version: '3.7'
services: 
    node-express:
        container_name: node-express
        image: node
        volumes: 
            - .:/api
        working_dir: /api
        user: node
        restart: always
        ports: 
            - "8002:8002"
        environment: 
            NODE_ENV: development
        command: npm start