version: '3.7'
services: 
  db:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    # volumes: 
    #   - $PWD/data:/var/lib/mysql
    environment: 
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: db
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbpass
    restart: always
    ports: 
      - "3306:3306"
#     networks: 
#       - my-net
# networks: 
#   my-net: